### ISSUE TITLE
Problem statement listed under client is static.

### ISSUE THREAD

**Issue by adityaB15** [sumantakollya/Old-Law-Management-System#1]
Legal problem registered by the client is not dynamically fetched from the database in the client display page.

![WhatsApp Image 2021-07-10 at 12 13 58](https://user-images.githubusercontent.com/87189868/125154643-93630f80-e178-11eb-87ad-100d2202eb80.jpeg)

**Comment by sumantakollya** [comment]
Client can issue and the details is dynamically fetched in the appointments view.
![image](https://user-images.githubusercontent.com/47918855/125160261-928ea580-e199-11eb-8a99-e14f153f2927.png)
