### ISSUE TITLE
Client personal information is static

### ISSUE THREAD

**Issue by adityaB15** [sumantakollya/Old-Law-Management-System#2]
The personal information of a client is not dynamically fetched for the client display page.

**Comment by Subhajit-P** [comment]
![1](https://user-images.githubusercontent.com/86721931/125155004-a8d93900-e17a-11eb-83c5-ea19e526c05f.jpeg)
![2](https://user-images.githubusercontent.com/86721931/125155006-ac6cc000-e17a-11eb-83a1-0929cef451db.jpeg)

Issue Resolved
