### ISSUE TITLE
Static display in Lawyer Dashboard 

### ISSUE THREAD

**Issue by adityaB15** [sumantakollya/Old-Law-Management-System#3]
The personal information of a lawyer is not dynamically fetched for the lawyer display page.
![Issue3](https://user-images.githubusercontent.com/87189868/125155139-8136a080-e17b-11eb-9467-8ba627834263.png)

**Comment by sumantakollya** [comment]
Appointments dynamically fetched from database.
![image](https://user-images.githubusercontent.com/47918855/125160379-1f396380-e19a-11eb-98e6-474349492b35.png)
